version: '3.7'
services:
  objectstorage:
    image: minio/minio
    ports:
      - "9090:9090" # api port to be closed
      - "9000:9000"
    networks:
      - localNetwork
    command: "server /data --address :9090 --console-address :9000"
  flask:
    image: highsparrow4reel/hand-writing-back:latest
    ports:
      - "5000:5000"
    networks:
      - localNetwork
    environment:
      - MINIO_ACCESS_KEY="minioadmin"
      - MINIO_SECRET_KEY="minioadmin" # how to write update after we get the actual key from minio container?
    depends_on:
      - objectstorage
  frontend:
    image: highsparrow4reel/hand-writing-front:latest
    ports:
      - "3000:3000"
    networks:
      - localNetwork

volumes:
  postgres-data:
  data:

networks:
  localNetwork: