version: '3.7'
services:
  objectstorage:
    image: minio/minio
    ports:
      - "9000:9000"
    networks:
      - localNetwork
    command: "server /data --address :9090 --console-address :9000"
  flask:
    build: flask/
    ports:
      - "5000:5000"
    networks:
      - localNetwork
    depends_on:
      - objectstorage
  frontend:
    build: frontend/
    ports:
      - "3000:3000"
    networks:
      - localNetwork

volumes:
  postgres-data:
  data:

networks:
  localNetwork:



    
# postgres:
#   image: postgres:latest
#   ports:
#     - "5432:5432"
#   networks:
#     - localNetwork
#   environment:
#     - POSTGRES_USER: <USERNAME>
#     - POSTGRES_PASSWORD: <PASSSSS>
#     - POSTGRES_DB: <DBNAME>
#   volumes:
#     - ./postgres-data:/var/lib/postgresql/data
# the actual pipeline
# pipe:
#   build: app/
#   ports:
#     - "80:80"
#   networks:
#     - localNetwork
#   depends_on:
#     - postgres
#     - objectstorage
# the frontend


# depends_on:
#   - pipe
# montring:
#   build: montring/
#   ports:
#     - "8080:8080"
#   networks:
#     - localNetwork
#   depends_on:
#     - pipe
#     - frontend
