services:
  objectstorage:
    name: objectstorage
    image: minio/minio
    entrypoint: 
      - "/bin/bash"
      - "minio "
      - "server"
      - "/data"
      - "--console-address: 9090"
      - "--address :9000"
    ports:
      - "9090:9090"
      - "9000:9000"
    volumes:
      - ./data:/data
    networks:
      - localNetwork
    environment:
      - MINIO_ROOT_USER: <USERNAME>
      - MINIO_ROOT_PASSWORD: <PASSSSS>
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - localNetwork
    environment:
      - POSTGRES_USER: <USERNAME>
      - POSTGRES_PASSWORD: <PASSSSS>
      - POSTGRES_DB: <DBNAME>
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # the actual pipeline
  pipe:
    build: app/
    ports:
      - "80:80"
    networks:
      - localNetwork
    depends_on:
      - postgres
      - objectstorage
  # the frontend
  frontend:
    build: frontend/
    ports:
      - "3000:3000"
    networks:
      - localNetwork
    depends_on:
      - pipe
  montring:
    build: montring/
    ports:
      - "8080:8080"
    networks:
      - localNetwork
    depends_on:
      - pipe
      - frontend

volumes:
  postgres-data:
  data:

networks:
  - localNetwork



    
